apiVersion: v1
kind: Service
metadata:
  labels:
    app: projector-frontend
  name: projector-frontend
  namespace: projector
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: projector-frontend