apiVersion: v1
kind: Service
metadata:
  labels:
    app: projector-frontend
  name: projector-frontend
  namespace: projector
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: projector-frontend